// Do not edit this file!
// Run IncludesUpdater.exe from tools directory to update.

// Includes
dofile("scripts/events/playerCommand.nut");
dofile("scripts/events/scriptInit.nut");
dofile("scripts/functions/str_replace.nut");
dofile("scripts/functions/getPlayerData.nut");
dofile("scripts/functions/tr.nut");

// Events
addEvent("playerCommand", onPlayerCommand);
addEvent("scriptInit", onScriptInit);
