// Do not edit this file!
// Run IncludesUpdater.exe from tools directory to update.

function onPlayerCommand(playerId, command)
{
	switch (command.slice(1))
	{
		default:
			dofile("scripts/commands/default.nut");
			return false;
	}
	return true;
}
